### PR TITLE
Fixes decimal tests to work across Node 8/10/12.

### LINKED ISSUE #399: Decimal Test Regression in Node v12
As mentioned in #380, there is an error around decimal tests when running under Node v12:

```
× Decimal - 123d-5 (0.002s)
AssertionError: numberValue(): expected 0.00123 to equal 0.0012300000000000002
  at test  <tests/unit/IonDecimalTest.js:194:20>
  at Test.123d-5 [as test]  <tests/unit/IonDecimalTest.js:50:33>
```

The regression is likely around floating point changes in the release, so one should probably look there first.

### PR DESCRIPTION
**Pull request by almann**
The underlying issue is that we test using `Decimal.numberValue()`
which uses `Math.pow(10, exponent)`.  This API has different rounding
behaviors (which is allowed by the ECMAScript spec) in v8/v10 of
Node vs. v12 of Node.  This is likely to be an issue on different
engines as well.

The fix allows the `test` method to support an inclusive interval of
valid `number` values that the `numberValue()` representation can be
and fixes the one test that seems to trip on this.

Resolves #399

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: tests/unit/IonDecimalTest.js [hunk 1]
```diff
@@ -175,6 +175,14 @@ define([
             'intValue(-1.0000001)': () => () => assert.equal(ion.Decimal.parse('-1.0000001').intValue(), -1),
         });
 
+        /**
+         * @param decimalString The text representation of the decimal to test.
+         * @param expectedCoefficient The expected `number` or `string` (LongInt) for the coefficient.
+         * @param expectedExponent The expected `number` or `string` (LongInt) for the exponent part.
```
Comment (pbcornell) [inline tests/unit/IonDecimalTest.js]: always a `number`;  i expect `string` to fail on `util._sign(expectedExponent)`

File: tests/unit/IonDecimalTest.js [hunk 2]
```diff
@@ -175,6 +175,14 @@ define([
             'intValue(-1.0000001)': () => () => assert.equal(ion.Decimal.parse('-1.0000001').intValue(), -1),
         });
 
+        /**
+         * @param decimalString The text representation of the decimal to test.
+         * @param expectedCoefficient The expected `number` or `string` (LongInt) for the coefficient.
```
Comment (pbcornell) [inline tests/unit/IonDecimalTest.js]: currently always a `string`, but agree a `number` could be passed

File: tests/unit/IonDecimalTest.js (hunk 1 above)
Comment (almann) [reply tests/unit/IonDecimalTest.js]: Oh interesting--I noted that it all plumbs down to `LongInt`, which is why I wrote it that way.
